spin_version = "1"
authors = ["Chris Matteson <chris.matteson@gmail.com>"]
description = ""
name = "openai-embeddings-ui"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
id = "openai-embeddings-ui"
files = [ { source = "static", destination = "/" } ]
[component.trigger]
route = "/..."

[[component]]
id = "api"
source = "api/target/api.wasm"
key_value_stores = ["default"]
allowed_http_hosts = ["https://api.openai.com"]
[component.trigger]
route = "/api"
[component.build]
command = "npm run build"
workdir = "api"

